spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springboot?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123
  messages:
    basename: i18n.login
  thymeleaf:
    cache: false
  mvc:
    static-path-pattern: static/**
    hiddenmethod:
      filter r:
        enabled: true
mybatis:
  type-aliases-package: com.edu.seiryo.entity
  mapper-locations: mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

